"""Bare Bones PSO Velocity Update Strategy.

Implementation of Bare Bones PSO by Kennedy (2003):
"Bare bones particle swarms"

Key Innovation: Eliminates velocity completely and uses Gaussian sampling
around the mean of personal best and global best positions. This creates
a parameter - free algorithm that automatically adjusts its exploration / exploitation.

Reference:
Kennedy, J. (2003). Bare bones particle swarms. Proceedings of the 2003 IEEE Swarm
Intelligence Symposium. SIS'03 (Cat. No.03EX706), 80 - 87.
"""

import numpy as np

from ..clamping.base import VelocityClampingStrategy
from ..clamping.velocity import NoClampingStrategy
from ..particles.base import ParticleBase
from .base import VelocityUpdateStrategy


class BareBonesPSOVelocityUpdate(VelocityUpdateStrategy):
    """
    Bare Bones PSO Velocity Update Strategy.
    In Bare Bones PSO, particles don't have velocities in the traditional sense.
    Instead, new positions are generated by sampling from a Gaussian distribution
    with mean = (personal_best + global_best) / 2 and standard deviation = |personal_best - global_best|.
    This creates a parameter - free algorithm that automatically adjusts exploration
    vs exploitation based on the difference between personal and global bests.
    The "velocity" returned by this strategy is actually the displacement from
    current position to the new sampled position, preserving the shared update signature.
    the standard PSO framework.
    Position Update Formula:
    For each dimension i:
    mean_i = (pbest_i + gbest_i) / 2
    std_i = |pbest_i - gbest_i|
    new_position_i = N(mean_i, std_i)  # Gaussian sampling
    velocity_i = new_position_i - current_position_i  # Computed displacement
    """

    def __init__(
        self,
        clamping_strategy: VelocityClampingStrategy | None = None,
        use_abs_std: bool = True,
        min_std: float = 1e-10,
    ):
        """
        Initialize the Bare Bones PSO velocity update strategy.
        Args:
            clamping_strategy: Strategy for velocity clamping. If None, NoClampingStrategy is used.
                             Note: For Bare Bones PSO, velocity clamping affects the computed
                             displacement, not the actual position sampling.
            use_abs_std: If True, use absolute difference for standard deviation.
                        If False, use the difference directly (can be negative).
            min_std: Minimum standard deviation to prevent zero variance sampling.
                    Small positive value to maintain exploration.
        """
        self.clamping_strategy = clamping_strategy or NoClampingStrategy()
        self.use_abs_std = use_abs_std
        self.min_std = max(min_std, 1e-10)  # Ensure minimum exploration

    def update(self, particle: ParticleBase, informant_position: np.ndarray, hyperparams: dict) -> np.ndarray:
        """
        Update a particle's "velocity" using Bare Bones PSO sampling.
        Args:
            particle: The particle whose velocity will be updated.
            _informant_position: Global best position (or best informant from topology).
            hyperparams: Dictionary containing the hyperparameters:
                * 'bounds' - tuple / list of (min, max) arrays for clamping (optional)
        Returns:
            Displacement vector (new_position - current_position) as "velocity".
        """
        bounds = hyperparams.get("bounds")
        # Get personal best and global best positions
        personal_best = particle.pbest
        global_best = informant_position
        rng = hyperparams.get("rng", np.random)
        # Calculate mean and standard deviation for Gaussian sampling
        mean = (personal_best + global_best) / 2.0
        # Calculate standard deviation (exploration parameter)
        std = np.abs(personal_best - global_best) if self.use_abs_std else personal_best - global_best
        # Ensure minimum standard deviation to maintain exploration
        std = np.maximum(std, self.min_std)
        # Sample new position from Gaussian distribution
        new_position = rng.normal(mean, std)
        # Calculate displacement (this becomes our "velocity")
        displacement = new_position - particle.position
        # Apply velocity clamping strategy to displacement
        if bounds is not None:
            clamped_displacement = self.clamping_strategy.clamp(displacement, bounds, hyperparams)
            displacement = np.asarray(clamped_displacement, dtype=np.float64)
        # Ensure we return a proper ndarray
        return np.asarray(displacement, dtype=np.float64)

    def get_required_hyperparams(self) -> list:
        """
        Get the list of required hyperparameters for Bare Bones PSO.
        Returns:
            Empty list as Bare Bones PSO is parameter - free.
        """
        return []

    def get_optional_hyperparams(self) -> dict:
        """
        Get the dictionary of optional hyperparameters with their default values.
        Returns:
            Dictionary of optional hyperparameter names and default values.
        """
        return {"bounds": None}

    def __str__(self) -> str:
        """String representation of the Bare Bones PSO velocity strategy."""
        return f"BareBonesPSOVelocityUpdate(use_abs_std={self.use_abs_std}, min_std={self.min_std:.2e})"

    def __repr__(self) -> str:
        """Detailed string representation of the Bare Bones PSO velocity strategy."""
        return (
            f"BareBonesPSOVelocityUpdate(use_abs_std={self.use_abs_std}, "
            f"min_std={self.min_std}, "
            f"clamping_strategy={type(self.clamping_strategy).__name__})"
        )
